### ISSUE TITLE
Doesn't appear to work when inverting 2x2 matrices.

### ISSUE THREAD

**Issue by caewok** [willnode/matrix-inversion#1]
Sort of trivial, but the code throws an error when trying to invert a 2x2 matrix:
`invert([[1, 2], [3, 4]])`

> VM100289:53 Uncaught TypeError: Cannot read properties of undefined (reading '1')
>     at optimizedNDet (<anonymous>:53:28)
>     at invert (<anonymous>:103:23)
>     at <anonymous>:1:1

Very helpful otherwise though, thanks!

**Comment by willnode** [comment]
Released as `v0.2.2`. Thanks!
